[package]
name = "void-desktop"
autobins = false
default-run = "void-desktop"
version = "0.1.0"
description = "VOID Desktop VPN client"
authors = ["VOID"]
edition = "2021"
[features]
dev-tools = []
[[bin]]
name = "void-desktop"
path = "src/main.rs"
[[bin]]
name = "void-tun-helper"
path = "src/bin/void-tun-helper.rs"
[[bin]]
name = "void-tun-smoke-controller"
path = "src/bin/void-tun-smoke-controller.rs"
[[bin]]
name = "void-dev-import-subscription"
path = "src/bin/void-dev-import-subscription.rs"
required-features = ["dev-tools"]
[lib]
name = "void_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
[build-dependencies]
tauri-build = { version = "2", features = [] }
[dependencies]
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
keyring = "4"
percent-encoding = "2"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "blocking", "json", "socks"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
url = "2"
uuid = { version = "1", features = ["v4", "serde"] }
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_Storage_FileSystem", "Win32_System_IO", "Win32_System_Pipes", "Win32_System_Threading", "Win32_System_Registry", "Win32_System_JobObjects", "Win32_UI_Shell", "Win32_NetworkManagement_IpHelper", "Win32_NetworkManagement_Ndis", "Win32_Networking_WinSock"] }
zip = { version = "2", default-features = false, features = ["deflate"] }
zeroize = "1"
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
