import { useEffect, useMemo, useState } from "react";
import { CircleHelp, Compass, Copy, Globe2, Layers3, Link2, LoaderCircle, Plus, Power, Radio, RefreshCw, ServerCog, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, X } from "lucide-react";
import "./App.css";
import { desktop } from "./lib/desktop";
import type { AppSnapshot, ConnectionState, CoreStatus, ServerSummary, Subscription } from "./lib/types";

type Page = "home" | "servers" | "subscriptions" | "settings";
const emptySnapshot: AppSnapshot = { connection: { kind: "idle" }, servers: [], subscriptions: [], selectedServerId: null };
const emptyCore: CoreStatus = { installState: "not_installed" };
const connectionLabel: Record<ConnectionState["kind"], string> = { idle: "Не подключено", preparing: "Подготовка", validating_config: "Проверка конфигурации", starting_core: "Запуск ядра", waiting_for_proxy: "Ожидание proxy", proxy_ready: "Proxy готов", connected: "Proxy готов", stopping: "Отключение", crashed: "Ядро завершилось", error: "Требуется действие" };

export default function App() {
  const [page, setPage] = useState<Page>("home"); const [snapshot, setSnapshot] = useState<AppSnapshot>(emptySnapshot); const [core, setCore] = useState<CoreStatus>(emptyCore); const [isImportOpen, setImportOpen] = useState(false); const [source, setSource] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  const refresh = async () => { const [nextSnapshot, nextCore] = await Promise.all([desktop.snapshot(), desktop.coreStatus()]); setSnapshot(nextSnapshot); setCore(nextCore); };
  useEffect(() => { void refresh().catch((error) => setNotice(String(error))); const timer = window.setInterval(() => void refresh().catch(() => undefined), 1000); return () => window.clearInterval(timer); }, []);
  const selected = useMemo(() => snapshot.servers.find((server) => server.id === snapshot.selectedServerId) ?? null, [snapshot]);
  async function importSource() { if (!source.trim()) return; setBusy(true); setNotice(null); try { const result = source.trim().match(/^(vless|vmess|ss|trojan):/i) ? await desktop.importUri(source.trim()) : await desktop.addSubscription(source.trim()); await refresh(); setSource(""); setImportOpen(false); setNotice(`Импортировано серверов: ${result.serverCount}`); } catch (error) { setNotice(error instanceof Error ? error.message : "Не удалось импортировать источник"); } finally { setBusy(false); } }
  async function selectServer(id: string | null) { await desktop.selectServer(id); await refresh(); }
  async function installCore() { setBusy(true); setNotice(null); try { setCore(await desktop.installCore()); } catch (error) { setNotice(error instanceof Error ? error.message : "Не удалось установить VPN core"); await refresh(); } finally { setBusy(false); } }
  async function toggleConnection() { setBusy(true); setNotice(null); try { snapshot.connection.kind === "connected" ? await desktop.disconnect() : await desktop.connect(); await refresh(); } catch (error) { await refresh(); setNotice(error instanceof Error ? error.message : "Не удалось изменить подключение"); } finally { setBusy(false); } }
  return <main className="app-shell"><aside className="sidebar" aria-label="Основная навигация"><div className="brand" onClick={() => setPage("home")} role="button" tabIndex={0}><span className="brand-mark"><span /></span><span>VOID</span></div><nav><NavItem active={page === "home"} icon={<Compass />} label="Обзор" onClick={() => setPage("home")} /><NavItem active={page === "servers"} icon={<ServerCog />} label="Серверы" onClick={() => setPage("servers")} /><NavItem active={page === "subscriptions"} icon={<Layers3 />} label="Подписки" onClick={() => setPage("subscriptions")} /><NavItem active={page === "settings"} icon={<Settings2 />} label="Настройки" onClick={() => setPage("settings")} /></nav><div className="sidebar-foot"><span className="live-dot" /> Proxy Mode · {core.installState === "ready" ? core.activeVersion : "core не установлен"}</div></aside><section className="content"><header className="topbar"><div><p className="eyebrow">PROXY MODE · СИСТЕМНЫЙ ТРАФИК НЕ ИЗМЕНЯЕТСЯ</p><h1>{page === "home" ? "Спокойное соединение" : page === "servers" ? "Точки выхода" : page === "subscriptions" ? "Источники доступа" : "Пространство настроек"}</h1></div><div className={`connection-chip ${snapshot.connection.kind}`}><span />{connectionLabel[snapshot.connection.kind]}</div></header>{notice && <div className="notice" role="status"><CircleHelp size={17}/><span>{notice}</span><button aria-label="Закрыть сообщение" onClick={() => setNotice(null)}><X size={17}/></button></div>}{page === "home" && <Home snapshot={snapshot} core={core} selected={selected} busy={busy} onInstall={installCore} onToggle={toggleConnection} onOpenImport={() => setImportOpen(true)} onServers={() => setPage("servers")} />}{page === "servers" && <Servers servers={snapshot.servers} selectedId={snapshot.selectedServerId} onSelect={selectServer} />}{page === "subscriptions" && <Subscriptions subscriptions={snapshot.subscriptions} onAdd={() => setImportOpen(true)} />}{page === "settings" && <Settings core={core} onInstall={installCore} busy={busy} />}</section>{isImportOpen && <ImportDialog value={source} busy={busy} onChange={setSource} onClose={() => setImportOpen(false)} onImport={importSource} />}</main>;
}
function NavItem({ active, icon, label, onClick }: { active: boolean; icon: React.ReactNode; label: string; onClick: () => void }) { return <button className={`nav-item ${active ? "active" : ""}`} onClick={onClick}>{icon}<span>{label}</span></button>; }
function Home({ snapshot, core, selected, busy, onInstall, onToggle, onOpenImport, onServers }: { snapshot: AppSnapshot; core: CoreStatus; selected: ServerSummary | null; busy: boolean; onInstall: () => void; onToggle: () => void; onOpenImport: () => void; onServers: () => void }) { const connected = snapshot.connection.kind === "connected"; const missing = core.installState !== "ready"; return <div className="home-view"><section className={`void-stage ${connected ? "is-connected" : ""}`}><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="void-core"><div className="core-flare" /></div><div className="stage-copy"><p>{connected ? "ЛОКАЛЬНЫЙ PROXY ГОТОВ" : missing ? "VPN CORE НЕ УСТАНОВЛЕН" : "ВАШ ЛОКАЛЬНЫЙ PROXY"}</p><h2>{connected ? "Proxy ready" : missing ? "Установите официальный Xray core" : "Нажмите, когда будете готовы"}</h2><span>{selected ? `${selected.name} · ${selected.country ?? "регион не указан"}` : "Автовыбор подберёт доступный сервер"}</span></div>{missing ? <button className="power-control" onClick={onInstall} disabled={busy}>{busy ? <LoaderCircle className="spin"/> : <Power />}<strong>Установить core</strong></button> : <button className="power-control" aria-label={connected ? "Отключиться" : "Подключиться"} onClick={onToggle} disabled={busy || snapshot.servers.length === 0}>{busy ? <LoaderCircle className="spin"/> : <Power />}<strong>{busy ? "Обрабатываем" : connected ? "Отключить" : "Подключиться"}</strong></button>}{!snapshot.servers.length && !missing && <button className="inline-link" onClick={onOpenImport}><Plus size={16}/> Добавить подписку, чтобы начать</button>}</section><section className="home-grid"><button className="server-pulse" onClick={onServers}><span className="pulse-icon"><Radio size={19}/></span><div><p>Активный маршрут</p><strong>{selected?.name ?? "AUTO — выбор ожидает данных"}</strong></div><span className="latency">{selected?.latencyMs ? `${selected.latencyMs} ms` : "—"}</span></button><div className="privacy-note"><ShieldCheck size={22}/><div><strong>Proxy Mode</strong><p>Системный трафик Windows не направляется через VPN.</p></div></div><div className="traffic-stat"><p>Состояние ядра</p><strong>{core.installState === "ready" ? core.activeVersion ?? "Готово" : "Не установлено"}</strong><span>{snapshot.connection.kind === "connected" ? "Proxy слушает loopback" : "Управляется backend"}</span></div></section></div>; }
function Servers({ servers, selectedId, onSelect }: { servers: ServerSummary[]; selectedId: string | null; onSelect: (id: string | null) => void }) { return <div className="servers-view"><button className={`auto-route ${selectedId === null ? "selected" : ""}`} onClick={() => onSelect(null)}><div className="auto-glyph"><Sparkles size={25}/></div><div><p>РЕЖИМ МАРШРУТИЗАЦИИ</p><h2>Автовыбор</h2><span>Стабильный сервер выбирается с запасом к переключению.</span></div><span className="selection-state">{selectedId === null ? "Активен" : "Выбрать"}</span></button><div className="section-heading"><div><p className="eyebrow">ДОСТУПНЫЕ УЗЛЫ</p><h2>{servers.length ? `${servers.length} сервер${servers.length === 1 ? "" : "а"}` : "Пока нет серверов"}</h2></div><button className="icon-action" title="Проверить состояние" disabled><RefreshCw size={18}/></button></div><div className="server-list">{servers.map((server) => <ServerRow key={server.id} server={server} chosen={server.id === selectedId} onChoose={() => onSelect(server.id)} />)}{!servers.length && <div className="empty-state"><Globe2 size={31}/><p>Импортируйте подписку или URI — серверы появятся здесь.</p></div>}</div></div>; }
function ServerRow({ server, chosen, onChoose }: { server: ServerSummary; chosen: boolean; onChoose: () => void }) { return <button className={`server-row ${chosen ? "chosen" : ""}`} onClick={onChoose}><span className="country-orb">{server.country?.slice(0, 2).toUpperCase() ?? "--"}</span><div className="server-main"><strong>{server.name}</strong><span>{server.protocol.toUpperCase()} · {server.transport ?? "TCP"} · {server.address}</span></div><span className={`health ${server.health.toLowerCase()}`}><i />{server.health === "UNKNOWN" ? "Нет пробы" : server.health}</span><span className="server-latency">{server.latencyMs ? `${server.latencyMs} ms` : "—"}</span></button>; }
function Subscriptions({ subscriptions, onAdd }: { subscriptions: Subscription[]; onAdd: () => void }) { return <div className="subscriptions-view"><section className="source-intro"><div><Link2 size={23}/><p className="eyebrow">SUBSCRIPTION MANAGER</p><h2>Один источник — актуальная карта серверов.</h2><p>Новая версия принимается только после проверки и разбора. Рабочая конфигурация не заменяется невалидными данными.</p></div><button className="primary-button" onClick={onAdd}><Plus size={18}/> Добавить источник</button></section><div className="source-stream">{subscriptions.map((sub) => <article key={sub.id} className="source-line"><span className="source-sigil"><Link2 size={18}/></span><div><strong>{sub.name}</strong><p>{sub.serverCount} серверов · обновлено {new Date(sub.updatedAt).toLocaleString("ru-RU")}</p></div><span className="verified"><ShieldCheck size={15}/> Проверено</span></article>)}{!subscriptions.length && <div className="empty-state wide"><Link2 size={31}/><p>Подписки ещё не добавлены. Поддерживаются HTTPS URL и VLESS, VMess, Shadowsocks, Trojan URI.</p></div>}</div></div>; }
function Settings({ core, onInstall, busy }: { core: CoreStatus; onInstall: () => void; busy: boolean }) { return <div className="settings-view"><section className="settings-lead"><SlidersHorizontal size={24}/><div><p className="eyebrow">PROXY MODE</p><h2>Сначала — предсказуемость.</h2><p>Системный DNS, маршруты и TUN-адаптер Windows пока не изменяются.</p></div></section><div className="settings-rows"><div><span>VPN core</span><strong>{core.installState === "ready" ? "Готов" : core.installState === "failed" ? "Ошибка" : "Не установлен"}</strong></div><div><span>Активная версия</span><strong>{core.activeVersion ?? "—"}</strong></div><div><span>Предыдущая версия</span><strong>{core.previousVersion ?? "—"}</strong></div><div><span>Последняя ошибка</span><strong>{core.lastError ?? "—"}</strong></div><div><span>Логирование</span><strong>INFO · с маскированием секретов</strong></div></div>{core.installState !== "ready" && <button className="primary-button" onClick={onInstall} disabled={busy}>{busy ? <LoaderCircle className="spin" size={17}/> : <Power size={17}/>} Установить официальный core</button>}</div>; }
function ImportDialog({ value, busy, onChange, onClose, onImport }: { value: string; busy: boolean; onChange: (value: string) => void; onClose: () => void; onImport: () => void }) { return <div className="modal-scrim" role="presentation"><section className="import-dialog" role="dialog" aria-modal="true" aria-labelledby="import-title"><button className="dialog-close" aria-label="Закрыть" onClick={onClose}><X size={18}/></button><div className="dialog-icon"><Link2 size={23}/></div><p className="eyebrow">НОВЫЙ ИСТОЧНИК</p><h2 id="import-title">Добавьте доступ</h2><p>Вставьте ссылку подписки HTTPS или один URI VLESS, VMess, Shadowsocks либо Trojan.</p><label htmlFor="source">Ссылка или URI</label><textarea id="source" autoFocus value={value} onChange={(event) => onChange(event.target.value)} placeholder="https://… или vless://…" rows={4}/><div className="dialog-actions"><button className="quiet-button" onClick={() => navigator.clipboard?.readText().then(onChange).catch(() => undefined)}><Copy size={16}/> Вставить из буфера</button><button className="primary-button" disabled={busy || !value.trim()} onClick={onImport}>{busy ? <LoaderCircle className="spin" size={17}/> : <Plus size={17}/>} Импортировать</button></div></section></div>; }
